dependencies:
    - smartcontractkit/chainlink@1.4.1
compiler:
    solc:
        remappings:
          - "@chainlink=smartcontractkit/chainlink@1.4.1"
networks:
  default: development
  development :
    eth_usd_price_feed: '0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419'
    vrf_coordinator: "0x6168499c0cFfCaCD319c818142124B7A15E857ab"
    fee : 
    keyhash : '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'

  rinkeby:
    vrf_coordinator: "0x6168499c0cFfCaCD319c818142124B7A15E857ab"
    eth_usd_price_feed :
    vrf_coordinator :
    verify : true

  mainnet-fork:
      eth_usd_price_feed: '0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419'
  wallets:
    from_key: $(PRIVATE_KEY)
