dependencies:
    - smartcontractkit/chainlink@1.4.1
compiler:
    solc:
        remappings:
          - "@chainlink=smartcontractkit/chainlink@1.4.1"
networks:
  default: development
  rinkeby:
    vrf_coordinator: "0x6168499c0cFfCaCD319c818142124B7A15E857ab"
  
  mainnet-fork:
      eth_usd_price_feed: '0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419'
  wallets:
    from_key: $(PRIVATE_KEY)
